### ISSUE TITLE
Kem Trait is not compatible with non DH-based algorithm

### ISSUE THREAD

**Issue by BoOTheFurious** [rozbb/rust-hpke#16] opened 2021-08-19 08:37 UTC
Hello,
I want to use the library with my own specific KEM algorithm implementing the `kem` trait (to benefit from the rfc framework).
The rfc allows the use of future KEM not based on DH but the library strongly rely on DH-based algorithm.
For instance the `EncappedKey` struct is forced to be a `PublicKey`, the `kex` is in fact the generation/decryption of the shared key (and thus differs from sender to receiver) whereas the `sk_to_pk` in `encap` is the encryption of the shared secret.
Thus is it possible to made those change to allow more generic KEM algo (ie not DH-based) ?

Note that if it’s ok I can try to make a PR about this

**Comment by rozbb** [comment] 2021-08-19 15:07
Thanks for bringing this up. This is a great point. I would absolutely accept a PR that makes the KEM backend more extensible

**Comment by rozbb** [comment] 2021-12-04 09:57
As mentioned in #17 I just made a big refactor that should hopefully address this. Please let me know if it's sufficient for your usecase

**Comment by rozbb** [comment] 2021-12-30 20:31
Closing. Feel free to reopen if you think the issue is not solved

**Closed by rozbb** 2021-12-30 20:31 UTC

**Comment by BoOTheFurious** [comment] 2022-04-05 22:45
Sorry for delay, I was on another project. That's a very great job !! thank  you !! I am updating my project, I will create new issues if necessary.
